#!/bin/bash
SRCDIR=`pwd`
cd org/eclipse/photran/internal/core/parser
cp GenericParseTreeVisitor.java $SRCDIR
rm -f *.java
java -Xmx256M -jar $SRCDIR/ludwig.jar \
	-shift T_COMMA "<IoControlSpecList>" \
	-reduce "<SFVarName>" "<SFDummyArgName>" \
	-package "org.eclipse.photran.internal.core.parser" \
	-parserClassName Parser \
	$SRCDIR/fortran95.bnf
for file in AST*Node.java; do
  patch $file <$SRCDIR/ASTNode.patch
done
patch ASTVisitor.java <$SRCDIR/ASTVisitor.patch
patch Parser.java <$SRCDIR/Parser.patch
for file in *.java; do
  patch $file <$SRCDIR/Copyright.patch
done
mv $SRCDIR/GenericParseTreeVisitor.java .
