#!/bin/bash
cd /home/joverbey/ludwig-workspace/bz.over.ludwig.ui.cmdline
./ludwig java2 acst /home/joverbey/photran/photran3-workspace/org.eclipse.photran.core/parser/fortran95.lr
cd /home/joverbey/photran/photran3-workspace/org.eclipse.photran.core/parser/org/eclipse/photran/internal/core/parser
sed -e "s/Yylex/ILexer/g; s/getNextToken/yylex/g" Parser.java >Parser.java.x
mv -f Parser.java.x Parser.java
sed -e "s/abstract int getActionRow();/int getActionRow() { return -9999; }/g;" Terminal.java >Terminal.java.x
mv -f Terminal.java.x Terminal.java
for file in *.java; do
  sed -e "s/package org.eclipse.photran.internal.core.parser;/package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;/g" $file >$file.x
  mv -f $file.x $file
done
rm -f Token.java
