#!/bin/sh
#
# Photran wrapper script
#
# Usage: photran_build [-t tag] [-d build_dir] [build_args]
#
# where
#
# tag is the CVS tag used to check out the releng project (default HEAD)
# build_dir is the location that the build will take place
# build_args are any arguments you want to pass to the build script
#
# set up anything environment specific that needs to be done before
# launching the build script in the releng project

TAG=HEAD
# main staging directory
BUILD_DIR=/opt/public/download-staging.priv/tools/ptp/releng
BUILD_LOG=$BUILD_DIR/photran_build_`date +%Y%m%d%H%M`.log

{

args=`getopt t: $*`

if [ $? != 0 ]; then
	echo "usage: photran_build [-t tag] [-d build_dir] [build_args]"
	exit 1
fi

set -- $args
for i
do
	case "$i"
	in
	-t) TAG="$2"; shift; shift;;
	-d) BUILD_DIR="$2"; shift; shift;;
	--) shift; break;;
	esac
done

# create the releng staging directory and go there
mkdir -p $BUILD_DIR && cd $BUILD_DIR

# remove the old build
rm -fr org.eclipse.photran

# Check out the releng project
export CVSROOT=:pserver:anonymous@dev.eclipse.org:/cvsroot/technology
cvs co -r $TAG -d org.eclipse.photran org.eclipse.photran/org.eclipse.photran.releng

# run the main script
cd org.eclipse.photran
sh build.sh $*

} >$BUILD_LOG 2>&1

if grep -q 'BUILD FAILED' $BUILD_LOG; then
	echo "BUILD FAILED. See $BUILD_LOG for details."
fi

exit 0

