#!/bin/sh
#
# This script is used to set up the project the first time you check it out of
# the CVS repository into Eclipse. It should not be needed to run thereafter.
#
export RUNTIME=orte
export PARENT=`dirname $PWD`
arch=`uname -p`
if [ -z "$arch" -o "$arch" = "unknown" ]; then
	arch=`uname -m`
fi
export ARCH=`echo $arch | sed -e 's/powerpc/ppc/' -e 's/ppc64/ppc/' -e 's/i.86/x86/'`export OS=`uname -s | sed -e 's/Darwin/macosx/' -e 's/Linux/linux/'`
export PREFIX=$PARENT/org.eclipse.ptp.debug.sdm.$RUNTIME.$OS.$ARCH

sh configure --prefix=$PREFIX
exit 0
