// Generated by Rex version 1.0 alpha 5

package org.eclipse.photran.internal.core.f95modelparser;


/**
 * Common superclass for Terminal and Nonterminal
 */
public abstract class TerminalOrNonterminal
{
    public abstract String getDescription();

    abstract int getNumberOfSymbolsOnValueStack();
}
