#!/bin/sh

#
# Create an update site archive and copy update site and archive up to eclipse.org
#
# NOTE: Tested on MacOS X only!
#

UPDATE=true
USER=gwatson

args=`getopt u:n $*`
if [ $? != 0 ]; then
	echo 'Usage: update_ptp [-u user] [-n]'
	exit 1
fi

set -- $args

for i; do
	case "$i" in
	-u) USER="$2"; shift;;
	-n) UPDATE=false; shift;;
	esac
done

TAR_CMD="tar --create --verbose --gzip --dereference --exclude=CVS --exclude=.DS_Store --exclude=.cvsignore --exclude=readme.txt"
ZIP_CMD="zip -r"
ZIP_EXCLUDES="-x \*CVS\* -x \*.DS_Store -x \*.cvsignore -x \*readme.txt"

RELEASE_DIR=downloads/tools/ptp/releases/2.0
SYSTEM=$USER@dev.eclipse.org
CORE=features/org.eclipse.ptp.core*
VERSION=`expr $CORE : 'features/org.eclipse.ptp.core_\(.*\).jar'`
NAME=ptp-updatesite-$VERSION

if [ ! -d $NAME ]; then
	mkdir $NAME
	(cd $NAME; \
	ln -s ../features; \
	ln -s ../plugins; \
	ln -s ../site.xml; \
	ln -s ../notice.html; \
	ln -s ../epl-v10.html)
fi

(cd $NAME; eval $ZIP_CMD ../$NAME.zip . $ZIP_EXCLUDES)

if [ $UPDATE = "true" ]; then
	(cd $NAME; \
	ln ../$NAME.zip; \
	$TAR_CMD --file=- .| \
	  ssh $SYSTEM "(cd $RELEASE_DIR; \
		rm -f plugins/*.jar; rm -f features/*.jar; \
		tar zxf -)"
	)
fi

rm -rf $NAME
exit 0
