#!/bin/sh
CLASSPATH=\
`echo $0 | sed -e "s/[^\/]*$//g; s/\/$//g"`/../distrib/photran-cmdline.jar:\
`echo $0 | sed -e "s/[^\/]*$//g; s/\/$//g"`/../bin
java -cp "$CLASSPATH" EvenMoreDefs $1 $2 $3 $4 $5 $6 $7 $8 $9
