#!/bin/sh
CLASSPATH=\
`echo $0 | sed -e "s/[^\/]*$//g; s/\/$//g"`/../distrib/photran-cmdline.jar:\
`echo $0 | sed -e "s/[^\/]*$//g; s/\/$//g"`/../bin
java -cp "$CLASSPATH" -Xrunhprof:cpu=samples,interval=20,depth=10 -Xmx256M ParseFixed $1 $2 $3 $4 $5 $6 $7 $8 $9
