#!/bin/sh
#
# script to update PTP versions
#
# Usage: update_versions ptp_version
#
# ptp_version - new version string for PTP (e.g. "5.0.1")
#
# Note: a "qualifier" suffix will automatically be added to the version where appropriate
#

TMP_DIR=/tmp

if [ $# -lt 1 ]; then
	echo "usage: update_versions ptp_version"
	exit 1
fi

ptp_version=$1

PTP_FEATURES="\
	org.eclipse.ptp-feature \
	org.eclipse.ptp.core-feature \
	org.eclipse.ptp.etfw-feature \
	org.eclipse.ptp.etfw.ppw-feature \
	org.eclipse.ptp.etfw.tau-feature \
	org.eclipse.ptp.etfw.tau.fortran-feature \
	org.eclipse.ptp.external-feature \
	org.eclipse.ptp.gem-feature \
	org.eclipse.ptp.master \
	org.eclipse.ptp.pldt-feature \
	org.eclipse.ptp.pldt.lapi-feature \
	org.eclipse.ptp.pldt.upc-feature \
	org.eclipse.ptp.rdt-feature \
	org.eclipse.ptp.rdt.remotejars-feature \
	org.eclipse.ptp.rdt.remotetools-feature \
	org.eclipse.ptp.rdt.sync-feature \
	org.eclipse.ptp.rdt.sync.fortran-feature \
	org.eclipse.ptp.rdt.xlc-feature \
	org.eclipse.ptp.remote-feature \
	org.eclipse.ptp.remote.remotetools-feature \
	org.eclipse.ptp.remote.rse-feature \
	org.eclipse.ptp.remotetools-feature \
	org.eclipse.ptp.rm.ibm.ll-feature \
	org.eclipse.ptp.rm.ibm.pe-feature \
	org.eclipse.ptp.rm.jaxb-feature \
	org.eclipse.ptp.rm.jaxb.contrib-feature \
	org.eclipse.ptp.rm.jaxb.pbs-feature \
	org.eclipse.ptp.rm.lml_jaxb-feature \
	org.eclipse.ptp.rm.lml-feature \
	org.eclipse.ptp.rm.mpich2-feature \
	org.eclipse.ptp.rm.openmpi-feature \
	org.eclipse.ptp.rm.slurm-feature \
	org.eclipse.ptp.sci-feature \
	org.eclipse.ptp.sdk-feature \
	org.eclipse.ptp.sdm-feature \
	org.eclipse.ptp.services-feature \
	org.eclipse.ptp.utils-feature"

PTP_PLUGINS="\
	releng/org.eclipse.ptp.aix.ppc \
	releng/org.eclipse.ptp.linux.ppc \
	releng/org.eclipse.ptp.linux.x86 \
	releng/org.eclipse.ptp.linux.x86_64 \
	releng/org.eclipse.ptp.macosx.ppc \
	releng/org.eclipse.ptp.macosx.x86 \
	releng/org.eclipse.ptp \
	debug/org.eclipse.ptp.debug.sdm \
	core/org.eclipse.ptp.proxy \
	rms/org.eclipse.ptp.rm.ibm.pe.proxy \
	rms/org.eclipse.ptp.rm.ibm.ll.proxy \
	rms/org.eclipse.ptp.rm.slurm.proxy \
	tools/sci/org.eclipse.ptp.sci \
	core/org.eclipse.ptp.utils"
	
update_feature() {
	sed -e "s/^\([ \t]*\)version=\"[0-9]\.[0-9]\.[0-9]\.qualifier\"/\1version=\"$2\.qualifier\"/" < releng/$1/feature.xml > $TMP_DIR/${1}_feature.xml
	mv $TMP_DIR/${1}_feature.xml releng/$1/feature.xml
}

update_manifest() {
	sed -e "s/^Bundle-Version: *[0-9]\.[0-9]\.[0-9]\.qualifier/Bundle-Version: $2.qualifier/" < $1/META-INF/MANIFEST.MF > $TMP_DIR/${1}_MANIFEST.MF
	mv $TMP_DIR/${1}_MANIFEST.MF $1/META-INF/MANIFEST.MF
}

for feature in $PTP_FEATURES; do
	echo "Updating $feature..."
	update_feature $feature $ptp_version
done

for plugin in $PTP_PLUGINS; do
	echo "Updating $plugin..."
	update_manifest $plugin $ptp_version
done

(cd releng/org.eclipse.ptp.repo && ant -DnewVersion="$ptp_version" -f fixModules.xml)

exit 0
