/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem */

#ifndef _Included_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
#define _Included_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
 * Method:    OMPIInit
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem_OMPIGetError
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
 * Method:    OMPIInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem_OMPIInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
 * Method:    OMPIFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem_OMPIFinalize
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
 * Method:    OMPIProgress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem_OMPIProgress
  (JNIEnv *, jobject);

/*
 * Class:     org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem
 * Method:    OMPIRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ptp_rtsystem_ompi_OMPIControlSystem_OMPIRun
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
