//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 09:26:24 AM EDT 
//


package org.eclipse.ptp.rm.lml.internal.core.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				describes a picture, which can be aligned
 * 			
 * 
 * <p>Java class for picture_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="picture_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="align" type="{http://eclipse.org/ptp/lml}align_type" default="CENTER" />
 *       &lt;attribute name="width" type="{http://eclipse.org/ptp/lml}percent_type" default="0.1" />
 *       &lt;attribute name="height" type="{http://eclipse.org/ptp/lml}percent_type" default="0.1" />
 *       &lt;attribute name="inneralign" type="{http://eclipse.org/ptp/lml}align_type" default="CENTER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "picture_type")
public class PictureType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String src;
    @XmlAttribute
    protected AlignType align;
    @XmlAttribute
    protected Double width;
    @XmlAttribute
    protected Double height;
    @XmlAttribute
    protected AlignType inneralign;

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link AlignType }
     *     
     */
    public AlignType getAlign() {
        if (align == null) {
            return AlignType.CENTER;
        } else {
            return align;
        }
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlignType }
     *     
     */
    public void setAlign(AlignType value) {
        this.align = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getWidth() {
        if (width == null) {
            return  0.1D;
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getHeight() {
        if (height == null) {
            return  0.1D;
        } else {
            return height;
        }
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the inneralign property.
     * 
     * @return
     *     possible object is
     *     {@link AlignType }
     *     
     */
    public AlignType getInneralign() {
        if (inneralign == null) {
            return AlignType.CENTER;
        } else {
            return inneralign;
        }
    }

    /**
     * Sets the value of the inneralign property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlignType }
     *     
     */
    public void setInneralign(AlignType value) {
        this.inneralign = value;
    }

}
