//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.10 at 09:53:19 AM CEST 
//


package org.eclipse.ptp.rm.lml.internal.core.elements;

import java.io.Serializable;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *     			A type for collecting request information. LML can be
 *     			used as communication language. The client sends layout
 *     			information and empty data-tags to the server. The
 *     			server returns the corresponding data.
 *     		
 * 
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="saveLayout" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="getDefaultData" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType")
public class RequestType  implements Serializable {

    @XmlAttribute
    protected Boolean saveLayout;
    @XmlAttribute
    protected Boolean getDefaultData;

    /**
     * Gets the value of the saveLayout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSaveLayout() {
        if (saveLayout == null) {
            return false;
        } else {
            return saveLayout;
        }
    }

    /**
     * Sets the value of the saveLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSaveLayout(Boolean value) {
        this.saveLayout = value;
    }

    /**
     * Gets the value of the getDefaultData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGetDefaultData() {
        if (getDefaultData == null) {
            return false;
        } else {
            return getDefaultData;
        }
    }

    /**
     * Sets the value of the getDefaultData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGetDefaultData(Boolean value) {
        this.getDefaultData = value;
    }

}
