//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.18 at 04:25:39 PM CDT 
//

package org.eclipse.ptp.etfw.jaxb.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.eclipse.ptp.etfw.jaxb.data package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _EtfwTool_QNAME = new QName("http://org.eclipse.ptp/etfw", "etfwTool"); //$NON-NLS-1$ //$NON-NLS-2$

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * org.eclipse.ptp.etfw.jaxb.data
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link EtfwToolProcessType }
	 * 
	 */
	public EtfwToolProcessType createEtfwToolProcessType() {
		return new EtfwToolProcessType();
	}

	/**
	 * Create an instance of {@link PostProcToolType }
	 * 
	 */
	public PostProcToolType createPostProcToolType() {
		return new PostProcToolType();
	}

	/**
	 * Create an instance of {@link ExecToolType }
	 * 
	 */
	public ExecToolType createExecToolType() {
		return new ExecToolType();
	}

	/**
	 * Create an instance of {@link BuildToolType }
	 * 
	 */
	public BuildToolType createBuildToolType() {
		return new BuildToolType();
	}

	/**
	 * Create an instance of {@link BuildToolType }
	 * 
	 */
	public ToolAppType createToolAppType() {
		return new ToolAppType();
	}

	/**
	 * Create an instance of {@link BuildToolType }
	 * 
	 */
	public ToolIOType createToolIOType() {
		return new ToolIOType();
	}

	/**
	 * Create an instance of {@link BuildToolType }
	 * 
	 */
	public ToolPaneType createToolPaneType() {
		return new ToolPaneType();
	}

	/**
	 * Create an instance of {@link ControlDataType }
	 * 
	 */
	public ControlDataType createControlDataType() {
		return new ControlDataType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EtfwToolProcessType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://org.eclipse.ptp/etfw", name = "etfwTool")
	public JAXBElement<EtfwToolProcessType> createEtfwTool(EtfwToolProcessType value) {
		return new JAXBElement<EtfwToolProcessType>(_EtfwTool_QNAME, EtfwToolProcessType.class, null, value);
	}

}
