#!/bin/bash
sleep 1
echo normal
echo iacat2
echo indprio
echo lincoln_nomss
echo cap1
echo lincoln_debug
echo long
echo iacat
echo industrial
echo lincoln
echo wide
echo nomss
echo debug
echo fernsler
echo iacat3
echo lincoln_cuda3.2