// Generated by Rex version 1.0 alpha 5

package org.eclipse.photran.internal.core.f95modelparser;


/**
 * Common superclass for Token and Nonterminal
 */
public interface ParserSymbol
{
    public abstract String getDescription();
}
