//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 09:26:24 AM EDT 
//


package org.eclipse.ptp.rm.lml.core.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Layout for a table
 * 
 * <p>Java class for tablelayout_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tablelayout_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eclipse.org/ptp/lml}componentlayout_type">
 *       &lt;sequence>
 *         &lt;element name="column" type="{http://eclipse.org/ptp/lml}columnlayout_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="contenthint" type="{http://eclipse.org/ptp/lml}content_type" default="other" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tablelayout_type", propOrder = {
    "column"
})
public class TablelayoutType
    extends ComponentlayoutType
{

    protected List<ColumnlayoutType> column;
    @XmlAttribute
    protected ContentType contenthint;

    /**
     * Gets the value of the column property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the column property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnlayoutType }
     * 
     * 
     */
    public List<ColumnlayoutType> getColumn() {
        if (column == null) {
            column = new ArrayList<ColumnlayoutType>();
        }
        return this.column;
    }

    /**
     * Gets the value of the contenthint property.
     * 
     * @return
     *     possible object is
     *     {@link ContentType }
     *     
     */
    public ContentType getContenthint() {
        if (contenthint == null) {
            return ContentType.OTHER;
        } else {
            return contenthint;
        }
    }

    /**
     * Sets the value of the contenthint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentType }
     *     
     */
    public void setContenthint(ContentType value) {
        this.contenthint = value;
    }

}
