// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <AllocationList> ::= Allocation:<Allocation> 
 * <AllocationList> ::= @:<AllocationList> tcomma:T_COMMA Allocation:<Allocation> 
 */
public class ASTAllocationListNode extends ParseTreeNode
{
    public ASTAllocationListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTAllocationNode getASTAllocation(int index)
    {
        ASTAllocationListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTAllocationListNode)node.getChild("@");
        return (ASTAllocationNode)node.getChild("Allocation");
    }

    public Token getASTTcomma(int index)
    {
        ASTAllocationListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTAllocationListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTAllocationListNode(this); }
}
