// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <AccessId> ::= GenericName:<GenericName> 
 * <AccessId> ::= GenericSpec:<GenericSpec> 
 */
public class ASTAccessIdNode extends ParseTreeNode
{
    public ASTAccessIdNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTGenericNameNode getASTGenericName()
    {
        return (ASTGenericNameNode)this.getChild("GenericName");
    }

    public ASTGenericSpecNode getASTGenericSpec()
    {
        return (ASTGenericSpecNode)this.getChild("GenericSpec");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTAccessIdNode(this); }
}
