// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <AllocateObject> ::= VariableName:<VariableName>  :production441
 * <AllocateObject> ::= AllocateObject:<AllocateObject> FieldSelector:<FieldSelector>  :production442
 */
public class ASTAllocateObjectNode extends ParseTreeNode
{
    public ASTAllocateObjectNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTVariableNameNode getASTVariableName()
    {
        return (ASTVariableNameNode)this.getChild("VariableName");
    }

    public ASTAllocateObjectNode getASTAllocateObject()
    {
        return (ASTAllocateObjectNode)this.getChild("AllocateObject");
    }

    public ASTFieldSelectorNode getASTFieldSelector()
    {
        return (ASTFieldSelectorNode)this.getChild("FieldSelector");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTAllocateObjectNode(this); }
}
