// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <ActionStmt> ::= ObsoleteActionStmt:<ObsoleteActionStmt> 
 * <ActionStmt> ::= AllocateStmt:<AllocateStmt> 
 * <ActionStmt> ::= AssignmentStmt:<AssignmentStmt> 
 * <ActionStmt> ::= BackspaceStmt:<BackspaceStmt> 
 * <ActionStmt> ::= CallStmt:<CallStmt> 
 * <ActionStmt> ::= CloseStmt:<CloseStmt> 
 * <ActionStmt> ::= ContinueStmt:<ContinueStmt> 
 * <ActionStmt> ::= CycleStmt:<CycleStmt> 
 * <ActionStmt> ::= DeallocateStmt:<DeallocateStmt> 
 * <ActionStmt> ::= EndfileStmt:<EndfileStmt> 
 * <ActionStmt> ::= ExitStmt:<ExitStmt> 
 * <ActionStmt> ::= ForallStmt:<ForallStmt> 
 * <ActionStmt> ::= GotoStmt:<GotoStmt> 
 * <ActionStmt> ::= IfStmt:<IfStmt> 
 * <ActionStmt> ::= InquireStmt:<InquireStmt> 
 * <ActionStmt> ::= NullifyStmt:<NullifyStmt> 
 * <ActionStmt> ::= OpenStmt:<OpenStmt> 
 * <ActionStmt> ::= PointerAssignmentStmt:<PointerAssignmentStmt> 
 * <ActionStmt> ::= PrintStmt:<PrintStmt> 
 * <ActionStmt> ::= ReadStmt:<ReadStmt> 
 * <ActionStmt> ::= ReturnStmt:<ReturnStmt> 
 * <ActionStmt> ::= RewindStmt:<RewindStmt> 
 * <ActionStmt> ::= StopStmt:<StopStmt> 
 * <ActionStmt> ::= WhereStmt:<WhereStmt> 
 * <ActionStmt> ::= WriteStmt:<WriteStmt> 
 * <ActionStmt> ::= AssignStmt:<AssignStmt> 
 * <ActionStmt> ::= AssignedGotoStmt:<AssignedGotoStmt> 
 * <ActionStmt> ::= PauseStmt:<PauseStmt> 
 */
public class ASTActionStmtNode extends ParseTreeNode
{
    public ASTActionStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTObsoleteActionStmtNode getASTObsoleteActionStmt()
    {
        return (ASTObsoleteActionStmtNode)this.getChild("ObsoleteActionStmt");
    }

    public ASTAllocateStmtNode getASTAllocateStmt()
    {
        return (ASTAllocateStmtNode)this.getChild("AllocateStmt");
    }

    public ASTAssignmentStmtNode getASTAssignmentStmt()
    {
        return (ASTAssignmentStmtNode)this.getChild("AssignmentStmt");
    }

    public ASTBackspaceStmtNode getASTBackspaceStmt()
    {
        return (ASTBackspaceStmtNode)this.getChild("BackspaceStmt");
    }

    public ASTCallStmtNode getASTCallStmt()
    {
        return (ASTCallStmtNode)this.getChild("CallStmt");
    }

    public ASTCloseStmtNode getASTCloseStmt()
    {
        return (ASTCloseStmtNode)this.getChild("CloseStmt");
    }

    public ASTContinueStmtNode getASTContinueStmt()
    {
        return (ASTContinueStmtNode)this.getChild("ContinueStmt");
    }

    public ASTCycleStmtNode getASTCycleStmt()
    {
        return (ASTCycleStmtNode)this.getChild("CycleStmt");
    }

    public ASTDeallocateStmtNode getASTDeallocateStmt()
    {
        return (ASTDeallocateStmtNode)this.getChild("DeallocateStmt");
    }

    public ASTEndfileStmtNode getASTEndfileStmt()
    {
        return (ASTEndfileStmtNode)this.getChild("EndfileStmt");
    }

    public ASTExitStmtNode getASTExitStmt()
    {
        return (ASTExitStmtNode)this.getChild("ExitStmt");
    }

    public ASTForallStmtNode getASTForallStmt()
    {
        return (ASTForallStmtNode)this.getChild("ForallStmt");
    }

    public ASTGotoStmtNode getASTGotoStmt()
    {
        return (ASTGotoStmtNode)this.getChild("GotoStmt");
    }

    public ASTIfStmtNode getASTIfStmt()
    {
        return (ASTIfStmtNode)this.getChild("IfStmt");
    }

    public ASTInquireStmtNode getASTInquireStmt()
    {
        return (ASTInquireStmtNode)this.getChild("InquireStmt");
    }

    public ASTNullifyStmtNode getASTNullifyStmt()
    {
        return (ASTNullifyStmtNode)this.getChild("NullifyStmt");
    }

    public ASTOpenStmtNode getASTOpenStmt()
    {
        return (ASTOpenStmtNode)this.getChild("OpenStmt");
    }

    public ASTPointerAssignmentStmtNode getASTPointerAssignmentStmt()
    {
        return (ASTPointerAssignmentStmtNode)this.getChild("PointerAssignmentStmt");
    }

    public ASTPrintStmtNode getASTPrintStmt()
    {
        return (ASTPrintStmtNode)this.getChild("PrintStmt");
    }

    public ASTReadStmtNode getASTReadStmt()
    {
        return (ASTReadStmtNode)this.getChild("ReadStmt");
    }

    public ASTReturnStmtNode getASTReturnStmt()
    {
        return (ASTReturnStmtNode)this.getChild("ReturnStmt");
    }

    public ASTRewindStmtNode getASTRewindStmt()
    {
        return (ASTRewindStmtNode)this.getChild("RewindStmt");
    }

    public ASTStopStmtNode getASTStopStmt()
    {
        return (ASTStopStmtNode)this.getChild("StopStmt");
    }

    public ASTWhereStmtNode getASTWhereStmt()
    {
        return (ASTWhereStmtNode)this.getChild("WhereStmt");
    }

    public ASTWriteStmtNode getASTWriteStmt()
    {
        return (ASTWriteStmtNode)this.getChild("WriteStmt");
    }

    public ASTAssignStmtNode getASTAssignStmt()
    {
        return (ASTAssignStmtNode)this.getChild("AssignStmt");
    }

    public ASTAssignedGotoStmtNode getASTAssignedGotoStmt()
    {
        return (ASTAssignedGotoStmtNode)this.getChild("AssignedGotoStmt");
    }

    public ASTPauseStmtNode getASTPauseStmt()
    {
        return (ASTPauseStmtNode)this.getChild("PauseStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTActionStmtNode(this); }
}
