// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <BlockDataSubprogram> ::= BlockDataStmt:<BlockDataStmt> BlockDataBody:<BlockDataBody> EndBlockDataStmt:<EndBlockDataStmt> 
 * <BlockDataSubprogram> ::= BlockDataStmt:<BlockDataStmt> EndBlockDataStmt:<EndBlockDataStmt> 
 */
public class ASTBlockDataSubprogramNode extends ParseTreeNode
{
    public ASTBlockDataSubprogramNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTBlockDataStmtNode getASTBlockDataStmt()
    {
        return (ASTBlockDataStmtNode)this.getChild("BlockDataStmt");
    }

    public ASTBlockDataBodyNode getASTBlockDataBody()
    {
        return (ASTBlockDataBodyNode)this.getChild("BlockDataBody");
    }

    public ASTEndBlockDataStmtNode getASTEndBlockDataStmt()
    {
        return (ASTEndBlockDataStmtNode)this.getChild("EndBlockDataStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTBlockDataSubprogramNode(this); }
}
