// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <ComponentArraySpec> ::= ExplicitShapeSpecList:<ExplicitShapeSpecList> 
 * <ComponentArraySpec> ::= DeferredShapeSpecList:<DeferredShapeSpecList> 
 */
public class ASTComponentArraySpecNode extends ParseTreeNode
{
    public ASTComponentArraySpecNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTExplicitShapeSpecListNode getASTExplicitShapeSpecList()
    {
        return (ASTExplicitShapeSpecListNode)this.getChild("ExplicitShapeSpecList");
    }

    public ASTDeferredShapeSpecListNode getASTDeferredShapeSpecList()
    {
        return (ASTDeferredShapeSpecListNode)this.getChild("DeferredShapeSpecList");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTComponentArraySpecNode(this); }
}
