// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <CharLenParamValue> ::= Expr:<Expr> 
 * <CharLenParamValue> ::= tasterisk:T_ASTERISK 
 */
public class ASTCharLenParamValueNode extends ParseTreeNode
{
    public ASTCharLenParamValueNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public Token getASTTasterisk()
    {
        return this.getChildToken("tasterisk");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTCharLenParamValueNode(this); }
}
