// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <DataIDoObjectList> ::= DataIDoObject:<DataIDoObject> 
 * <DataIDoObjectList> ::= @:<DataIDoObjectList> tcomma:T_COMMA DataIDoObject:<DataIDoObject> 
 */
public class ASTDataIDoObjectListNode extends ParseTreeNode
{
    public ASTDataIDoObjectListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTDataIDoObjectNode getASTDataIDoObject(int index)
    {
        ASTDataIDoObjectListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataIDoObjectListNode)node.getChild("@");
        return (ASTDataIDoObjectNode)node.getChild("DataIDoObject");
    }

    public Token getASTTcomma(int index)
    {
        ASTDataIDoObjectListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataIDoObjectListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDataIDoObjectListNode(this); }
}
