// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <DataStmtObject> ::= Variable:<Variable> 
 * <DataStmtObject> ::= DataImpliedDo:<DataImpliedDo> 
 */
public class ASTDataStmtObjectNode extends ParseTreeNode
{
    public ASTDataStmtObjectNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTVariableNode getASTVariable()
    {
        return (ASTVariableNode)this.getChild("Variable");
    }

    public ASTDataImpliedDoNode getASTDataImpliedDo()
    {
        return (ASTDataImpliedDoNode)this.getChild("DataImpliedDo");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDataStmtObjectNode(this); }
}
