// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <DerivedTypeDef> ::= DerivedTypeStmt:<DerivedTypeStmt> DerivedTypeBody:<DerivedTypeBody> EndTypeStmt:<EndTypeStmt> 
 */
public class ASTDerivedTypeDefNode extends ParseTreeNode
{
    public ASTDerivedTypeDefNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTDerivedTypeStmtNode getASTDerivedTypeStmt()
    {
        return (ASTDerivedTypeStmtNode)this.getChild("DerivedTypeStmt");
    }

    public ASTDerivedTypeBodyNode getASTDerivedTypeBody()
    {
        return (ASTDerivedTypeBodyNode)this.getChild("DerivedTypeBody");
    }

    public ASTEndTypeStmtNode getASTEndTypeStmt()
    {
        return (ASTEndTypeStmtNode)this.getChild("EndTypeStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDerivedTypeDefNode(this); }
}
