// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <DerivedTypeBodyConstruct> ::= PrivateSequenceStmt:<PrivateSequenceStmt> 
 * <DerivedTypeBodyConstruct> ::= ComponentDefStmt:<ComponentDefStmt> 
 */
public class ASTDerivedTypeBodyConstructNode extends ParseTreeNode
{
    public ASTDerivedTypeBodyConstructNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTPrivateSequenceStmtNode getASTPrivateSequenceStmt()
    {
        return (ASTPrivateSequenceStmtNode)this.getChild("PrivateSequenceStmt");
    }

    public ASTComponentDefStmtNode getASTComponentDefStmt()
    {
        return (ASTComponentDefStmtNode)this.getChild("ComponentDefStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDerivedTypeBodyConstructNode(this); }
}
