// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <DataStmt> ::= LblDef:<LblDef> tdata:T_DATA Datalist:<Datalist> teos:T_EOS  :production350
 */
public class ASTDataStmtNode extends ParseTreeNode
{
    public ASTDataStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblDefNode getASTLblDef()
    {
        return (ASTLblDefNode)this.getChild("LblDef");
    }

    public Token getASTTdata()
    {
        return this.getChildToken("tdata");
    }

    public ASTDatalistNode getASTDatalist()
    {
        return (ASTDatalistNode)this.getChild("Datalist");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDataStmtNode(this); }
}
