// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <DataStmtConstant> ::= Constant:<Constant> 
 * <DataStmtConstant> ::= tnull:T_NULL tlparen:T_LPAREN trparen:T_RPAREN 
 */
public class ASTDataStmtConstantNode extends ParseTreeNode
{
    public ASTDataStmtConstantNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTConstantNode getASTConstant()
    {
        return (ASTConstantNode)this.getChild("Constant");
    }

    public Token getASTTnull()
    {
        return this.getChildToken("tnull");
    }

    public Token getASTTlparen()
    {
        return this.getChildToken("tlparen");
    }

    public Token getASTTrparen()
    {
        return this.getChildToken("trparen");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDataStmtConstantNode(this); }
}
