// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <DataRef> ::= varName:<Name>  :production408
 * <DataRef> ::= @:<DataRef> ( tlparen:T_LPAREN SectionSubscriptList:<SectionSubscriptList> trparen:T_RPAREN )? tpercent:T_PERCENT componentName:<Name>  :production409
 */
public class ASTDataRefNode extends ParseTreeNode
{
    public ASTDataRefNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTNameNode getASTVarName(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return (ASTNameNode)node.getChild("varName");
    }

    public Token getASTTlparen(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return node.getChildToken("tlparen");
    }

    public ASTSectionSubscriptListNode getASTSectionSubscriptList(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return (ASTSectionSubscriptListNode)node.getChild("SectionSubscriptList");
    }

    public Token getASTTrparen(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return node.getChildToken("trparen");
    }

    public Token getASTTpercent(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return node.getChildToken("tpercent");
    }

    public ASTNameNode getASTComponentName(int index)
    {
        ASTDataRefNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTDataRefNode)node.getChild("@");
        return (ASTNameNode)node.getChild("componentName");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTDataRefNode(this); }
}
