// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <ExecutableProgram> ::= ProgramUnit:<ProgramUnit>  :production1
 * <ExecutableProgram> ::= @:<ExecutableProgram> ProgramUnit:<ProgramUnit>  :production2
 */
public class ASTExecutableProgramNode extends ParseTreeNode
{
    public ASTExecutableProgramNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTProgramUnitNode getASTProgramUnit(int index)
    {
        ASTExecutableProgramNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTExecutableProgramNode)node.getChild("@");
        return (ASTProgramUnitNode)node.getChild("ProgramUnit");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTExecutableProgramNode(this); }
}
