// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <Expr> ::= Level5Expr:<Level5Expr> 
 * <Expr> ::= Expr:<Expr> DefinedBinaryOp:<DefinedBinaryOp> Level5Expr:<Level5Expr> 
 */
public class ASTExprNode extends ParseTreeNode
{
    public ASTExprNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLevel5ExprNode getASTLevel5Expr()
    {
        return (ASTLevel5ExprNode)this.getChild("Level5Expr");
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public ASTDefinedBinaryOpNode getASTDefinedBinaryOp()
    {
        return (ASTDefinedBinaryOpNode)this.getChild("DefinedBinaryOp");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTExprNode(this); }
}
