// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <ElsewherePart> ::= EndWhereStmt:<EndWhereStmt>  :production549
 * <ElsewherePart> ::= WhereBodyConstructBlock:<WhereBodyConstructBlock> EndWhereStmt:<EndWhereStmt>  :production550
 */
public class ASTElsewherePartNode extends ParseTreeNode
{
    public ASTElsewherePartNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTEndWhereStmtNode getASTEndWhereStmt()
    {
        return (ASTEndWhereStmtNode)this.getChild("EndWhereStmt");
    }

    public ASTWhereBodyConstructBlockNode getASTWhereBodyConstructBlock()
    {
        return (ASTWhereBodyConstructBlockNode)this.getChild("WhereBodyConstructBlock");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTElsewherePartNode(this); }
}
