// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <EquivalenceObject> ::= Variable:<Variable> 
 */
public class ASTEquivalenceObjectNode extends ParseTreeNode
{
    public ASTEquivalenceObjectNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTVariableNode getASTVariable()
    {
        return (ASTVariableNode)this.getChild("Variable");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTEquivalenceObjectNode(this); }
}
