// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <FormatIdentifier> ::= LblRef:<LblRef> 
 * <FormatIdentifier> ::= CExpr:<CExpr> 
 * <FormatIdentifier> ::= tasterisk:T_ASTERISK 
 */
public class ASTFormatIdentifierNode extends ParseTreeNode
{
    public ASTFormatIdentifierNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblRefNode getASTLblRef()
    {
        return (ASTLblRefNode)this.getChild("LblRef");
    }

    public ASTCExprNode getASTCExpr()
    {
        return (ASTCExprNode)this.getChild("CExpr");
    }

    public Token getASTTasterisk()
    {
        return this.getChildToken("tasterisk");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTFormatIdentifierNode(this); }
}
