// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <FunctionPars> ::= empty :production893
 * <FunctionPars> ::= FunctionPar:<FunctionPar>  :production894
 * <FunctionPars> ::= @:<FunctionPars> tcomma:T_COMMA FunctionPar:<FunctionPar>  :production895
 */
public class ASTFunctionParsNode extends ParseTreeNode
{
    public ASTFunctionParsNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTFunctionParNode getASTFunctionPar(int index)
    {
        ASTFunctionParsNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTFunctionParsNode)node.getChild("@");
        return (ASTFunctionParNode)node.getChild("FunctionPar");
    }

    public Token getASTTcomma(int index)
    {
        ASTFunctionParsNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTFunctionParsNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTFunctionParsNode(this); }
}
