// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <FunctionInterfaceRange> ::= SubprogramInterfaceBody:<SubprogramInterfaceBody> EndFunctionStmt:<EndFunctionStmt>  :production854
 * <FunctionInterfaceRange> ::= EndFunctionStmt:<EndFunctionStmt>  :production855
 */
public class ASTFunctionInterfaceRangeNode extends ParseTreeNode
{
    public ASTFunctionInterfaceRangeNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTSubprogramInterfaceBodyNode getASTSubprogramInterfaceBody()
    {
        return (ASTSubprogramInterfaceBodyNode)this.getChild("SubprogramInterfaceBody");
    }

    public ASTEndFunctionStmtNode getASTEndFunctionStmt()
    {
        return (ASTEndFunctionStmtNode)this.getChild("EndFunctionStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTFunctionInterfaceRangeNode(this); }
}
