// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <GenericSpec> ::= toperator:T_OPERATOR tlparen:T_LPAREN DefinedOperator:<DefinedOperator> trparen:T_RPAREN  :production864
 * <GenericSpec> ::= tassignment:T_ASSIGNMENT tlparen:T_LPAREN tequals:T_EQUALS trparen:T_RPAREN  :production865
 */
public class ASTGenericSpecNode extends ParseTreeNode
{
    public ASTGenericSpecNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTToperator()
    {
        return this.getChildToken("toperator");
    }

    public Token getASTTlparen()
    {
        return this.getChildToken("tlparen");
    }

    public ASTDefinedOperatorNode getASTDefinedOperator()
    {
        return (ASTDefinedOperatorNode)this.getChild("DefinedOperator");
    }

    public Token getASTTrparen()
    {
        return this.getChildToken("trparen");
    }

    public Token getASTTassignment()
    {
        return this.getChildToken("tassignment");
    }

    public Token getASTTequals()
    {
        return this.getChildToken("tequals");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTGenericSpecNode(this); }
}
