// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <IfConstruct> ::= IfThenStmt:<IfThenStmt> ThenPart:<ThenPart> 
 */
public class ASTIfConstructNode extends ParseTreeNode
{
    public ASTIfConstructNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTIfThenStmtNode getASTIfThenStmt()
    {
        return (ASTIfThenStmtNode)this.getChild("IfThenStmt");
    }

    public ASTThenPartNode getASTThenPart()
    {
        return (ASTThenPartNode)this.getChild("ThenPart");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTIfConstructNode(this); }
}
