// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <ImplicitSpecList> ::= ImplicitSpec:<ImplicitSpec> 
 * <ImplicitSpecList> ::= @:<ImplicitSpecList> tcomma:T_COMMA ImplicitSpec:<ImplicitSpec> 
 */
public class ASTImplicitSpecListNode extends ParseTreeNode
{
    public ASTImplicitSpecListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTImplicitSpecNode getASTImplicitSpec(int index)
    {
        ASTImplicitSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTImplicitSpecListNode)node.getChild("@");
        return (ASTImplicitSpecNode)node.getChild("ImplicitSpec");
    }

    public Token getASTTcomma(int index)
    {
        ASTImplicitSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTImplicitSpecListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTImplicitSpecListNode(this); }
}
