// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <InterfaceStmt> ::= LblDef:<LblDef> tinterface:T_INTERFACE GenericName:<GenericName> teos:T_EOS 
 * <InterfaceStmt> ::= LblDef:<LblDef> tinterface:T_INTERFACE GenericSpec:<GenericSpec> teos:T_EOS 
 * <InterfaceStmt> ::= LblDef:<LblDef> tinterface:T_INTERFACE teos:T_EOS 
 */
public class ASTInterfaceStmtNode extends ParseTreeNode
{
    public ASTInterfaceStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblDefNode getASTLblDef()
    {
        return (ASTLblDefNode)this.getChild("LblDef");
    }

    public Token getASTTinterface()
    {
        return this.getChildToken("tinterface");
    }

    public ASTGenericNameNode getASTGenericName()
    {
        return (ASTGenericNameNode)this.getChild("GenericName");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    public ASTGenericSpecNode getASTGenericSpec()
    {
        return (ASTGenericSpecNode)this.getChild("GenericSpec");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTInterfaceStmtNode(this); }
}
