// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <InputItem> ::= Variable:<Variable>  :production733
 * <InputItem> ::= InputImpliedDo:<InputImpliedDo>  :production734
 */
public class ASTInputItemNode extends ParseTreeNode
{
    public ASTInputItemNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTVariableNode getASTVariable()
    {
        return (ASTVariableNode)this.getChild("Variable");
    }

    public ASTInputImpliedDoNode getASTInputImpliedDo()
    {
        return (ASTInputImpliedDoNode)this.getChild("InputImpliedDo");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTInputItemNode(this); }
}
