// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <InputItemList> ::= InputItem:<InputItem> 
 * <InputItemList> ::= @:<InputItemList> tcomma:T_COMMA InputItem:<InputItem> 
 */
public class ASTInputItemListNode extends ParseTreeNode
{
    public ASTInputItemListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTInputItemNode getASTInputItem(int index)
    {
        ASTInputItemListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTInputItemListNode)node.getChild("@");
        return (ASTInputItemNode)node.getChild("InputItem");
    }

    public Token getASTTcomma(int index)
    {
        ASTInputItemListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTInputItemListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTInputItemListNode(this); }
}
