// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <KindParam> ::= ticon:T_ICON 
 * <KindParam> ::= NamedConstantUse:<NamedConstantUse> 
 */
public class ASTKindParamNode extends ParseTreeNode
{
    public ASTKindParamNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTicon()
    {
        return this.getChildToken("ticon");
    }

    public ASTNamedConstantUseNode getASTNamedConstantUse()
    {
        return (ASTNamedConstantUseNode)this.getChild("NamedConstantUse");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTKindParamNode(this); }
}
