// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <LowerBound> ::= Expr:<Expr>  :production293
 */
public class ASTLowerBoundNode extends ParseTreeNode
{
    public ASTLowerBoundNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTLowerBoundNode(this); }
}
