// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <Level1Expr> ::= Primary:<Primary>  :production477
 * <Level1Expr> ::= DefinedUnaryOp:<DefinedUnaryOp> Primary:<Primary>  :production478
 */
public class ASTLevel1ExprNode extends ParseTreeNode
{
    public ASTLevel1ExprNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTPrimaryNode getASTPrimary()
    {
        return (ASTPrimaryNode)this.getChild("Primary");
    }

    public ASTDefinedUnaryOpNode getASTDefinedUnaryOp()
    {
        return (ASTDefinedUnaryOpNode)this.getChild("DefinedUnaryOp");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTLevel1ExprNode(this); }
}
