// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <Level5Expr> ::= ( Level5Expr:<Level5Expr> EquivOp:<EquivOp> )? EquivOperand:<EquivOperand>  :production496
 */
public class ASTLevel5ExprNode extends ParseTreeNode
{
    public ASTLevel5ExprNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLevel5ExprNode getASTLevel5Expr()
    {
        return (ASTLevel5ExprNode)this.getChild("Level5Expr");
    }

    public ASTEquivOpNode getASTEquivOp()
    {
        return (ASTEquivOpNode)this.getChild("EquivOp");
    }

    public ASTEquivOperandNode getASTEquivOperand()
    {
        return (ASTEquivOperandNode)this.getChild("EquivOperand");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTLevel5ExprNode(this); }
}
