// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <MainRange> ::= Body:<Body> EndProgramStmt:<EndProgramStmt> 
 * <MainRange> ::= BodyPlusInternals:<BodyPlusInternals> EndProgramStmt:<EndProgramStmt> 
 * <MainRange> ::= EndProgramStmt:<EndProgramStmt> 
 */
public class ASTMainRangeNode extends ParseTreeNode
{
    public ASTMainRangeNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTBodyNode getASTBody()
    {
        return (ASTBodyNode)this.getChild("Body");
    }

    public ASTEndProgramStmtNode getASTEndProgramStmt()
    {
        return (ASTEndProgramStmtNode)this.getChild("EndProgramStmt");
    }

    public ASTBodyPlusInternalsNode getASTBodyPlusInternals()
    {
        return (ASTBodyPlusInternalsNode)this.getChild("BodyPlusInternals");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTMainRangeNode(this); }
}
