// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <NamedConstant> ::= tident:T_IDENT 
 */
public class ASTNamedConstantNode extends ParseTreeNode
{
    public ASTNamedConstantNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTident()
    {
        return this.getChildToken("tident");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTNamedConstantNode(this); }
}
