// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <Only> ::= GenericSpec:<GenericSpec> 
 * <Only> ::= tident:T_IDENT teqgreaterthan:T_EQGREATERTHAN UseName:<UseName> 
 * <Only> ::= UseName:<UseName> 
 */
public class ASTOnlyNode extends ParseTreeNode
{
    public ASTOnlyNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTGenericSpecNode getASTGenericSpec()
    {
        return (ASTGenericSpecNode)this.getChild("GenericSpec");
    }

    public Token getASTTident()
    {
        return this.getChildToken("tident");
    }

    public Token getASTTeqgreaterthan()
    {
        return this.getChildToken("teqgreaterthan");
    }

    public ASTUseNameNode getASTUseName()
    {
        return (ASTUseNameNode)this.getChild("UseName");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTOnlyNode(this); }
}
