// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <OutputItemList> ::= Expr:<Expr> 
 * <OutputItemList> ::= OutputItemList1:<OutputItemList1> 
 */
public class ASTOutputItemListNode extends ParseTreeNode
{
    public ASTOutputItemListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public ASTOutputItemList1Node getASTOutputItemList1()
    {
        return (ASTOutputItemList1Node)this.getChild("OutputItemList1");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTOutputItemListNode(this); }
}
