// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <OrOp> ::= tor:T_OR 
 */
public class ASTOrOpNode extends ParseTreeNode
{
    public ASTOrOpNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTor()
    {
        return this.getChildToken("tor");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTOrOpNode(this); }
}
