// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <OrOperand> ::= ( OrOperand:<OrOperand> AndOp:<AndOp> )? AndOperand:<AndOperand> 
 */
public class ASTOrOperandNode extends ParseTreeNode
{
    public ASTOrOperandNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTOrOperandNode getASTOrOperand()
    {
        return (ASTOrOperandNode)this.getChild("OrOperand");
    }

    public ASTAndOpNode getASTAndOp()
    {
        return (ASTAndOpNode)this.getChild("AndOp");
    }

    public ASTAndOperandNode getASTAndOperand()
    {
        return (ASTAndOperandNode)this.getChild("AndOperand");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTOrOperandNode(this); }
}
