// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <PointerStmt> ::= LblDef:<LblDef> tpointer:T_POINTER ( tcolon:T_COLON tcolon2:T_COLON )? PointerStmtObjectList:<PointerStmtObjectList> teos:T_EOS  :production334
 */
public class ASTPointerStmtNode extends ParseTreeNode
{
    public ASTPointerStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblDefNode getASTLblDef()
    {
        return (ASTLblDefNode)this.getChild("LblDef");
    }

    public Token getASTTpointer()
    {
        return this.getChildToken("tpointer");
    }

    public Token getASTTcolon()
    {
        return this.getChildToken("tcolon");
    }

    public Token getASTTcolon2()
    {
        return this.getChildToken("tcolon2");
    }

    public ASTPointerStmtObjectListNode getASTPointerStmtObjectList()
    {
        return (ASTPointerStmtObjectListNode)this.getChild("PointerStmtObjectList");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTPointerStmtNode(this); }
}
