// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <PositionSpecList> ::= UnitIdentifier:<UnitIdentifier> tcomma:T_COMMA PositionSpec:<PositionSpec>  :production756
 * <PositionSpecList> ::= PositionSpec:<PositionSpec>  :production757
 * <PositionSpecList> ::= @:<PositionSpecList> tcomma:T_COMMA PositionSpec:<PositionSpec>  :production758
 */
public class ASTPositionSpecListNode extends ParseTreeNode
{
    public ASTPositionSpecListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTUnitIdentifierNode getASTUnitIdentifier(int index)
    {
        ASTPositionSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPositionSpecListNode)node.getChild("@");
        return (ASTUnitIdentifierNode)node.getChild("UnitIdentifier");
    }

    public Token getASTTcomma(int index)
    {
        ASTPositionSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPositionSpecListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    public ASTPositionSpecNode getASTPositionSpec(int index)
    {
        ASTPositionSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPositionSpecListNode)node.getChild("@");
        return (ASTPositionSpecNode)node.getChild("PositionSpec");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTPositionSpecListNode(this); }
}
