// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <PrefixSpecList> ::= PrefixSpec:<PrefixSpec> 
 * <PrefixSpecList> ::= @:<PrefixSpecList> PrefixSpec:<PrefixSpec> 
 */
public class ASTPrefixSpecListNode extends ParseTreeNode
{
    public ASTPrefixSpecListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTPrefixSpecNode getASTPrefixSpec(int index)
    {
        ASTPrefixSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPrefixSpecListNode)node.getChild("@");
        return (ASTPrefixSpecNode)node.getChild("PrefixSpec");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTPrefixSpecListNode(this); }
}
