// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <PointerObjectList> ::= PointerObject:<PointerObject>  :production444
 * <PointerObjectList> ::= @:<PointerObjectList> tcomma:T_COMMA PointerObject:<PointerObject>  :production445
 */
public class ASTPointerObjectListNode extends ParseTreeNode
{
    public ASTPointerObjectListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTPointerObjectNode getASTPointerObject(int index)
    {
        ASTPointerObjectListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPointerObjectListNode)node.getChild("@");
        return (ASTPointerObjectNode)node.getChild("PointerObject");
    }

    public Token getASTTcomma(int index)
    {
        ASTPointerObjectListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTPointerObjectListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTPointerObjectListNode(this); }
}
