// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <PointerAssignmentStmt> ::= LblDef:<LblDef> Name:<Name> teqgreaterthan:T_EQGREATERTHAN Target:<Target> teos:T_EOS 
 * <PointerAssignmentStmt> ::= LblDef:<LblDef> Name:<Name> tpercent:T_PERCENT DataRef:<DataRef> teqgreaterthan:T_EQGREATERTHAN Target:<Target> teos:T_EOS 
 * <PointerAssignmentStmt> ::= LblDef:<LblDef> Name:<Name> tlparen:T_LPAREN SFExprList:<SFExprList> trparen:T_RPAREN tpercent:T_PERCENT DataRef:<DataRef> teqgreaterthan:T_EQGREATERTHAN Target:<Target> teos:T_EOS 
 * <PointerAssignmentStmt> ::= LblDef:<LblDef> Name:<Name> tlparen:T_LPAREN SFDummyArgNameList:<SFDummyArgNameList> trparen:T_RPAREN tpercent:T_PERCENT DataRef:<DataRef> teqgreaterthan:T_EQGREATERTHAN Target:<Target> teos:T_EOS 
 */
public class ASTPointerAssignmentStmtNode extends ParseTreeNode
{
    public ASTPointerAssignmentStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblDefNode getASTLblDef()
    {
        return (ASTLblDefNode)this.getChild("LblDef");
    }

    public ASTNameNode getASTName()
    {
        return (ASTNameNode)this.getChild("Name");
    }

    public Token getASTTeqgreaterthan()
    {
        return this.getChildToken("teqgreaterthan");
    }

    public ASTTargetNode getASTTarget()
    {
        return (ASTTargetNode)this.getChild("Target");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    public Token getASTTpercent()
    {
        return this.getChildToken("tpercent");
    }

    public ASTDataRefNode getASTDataRef()
    {
        return (ASTDataRefNode)this.getChild("DataRef");
    }

    public Token getASTTlparen()
    {
        return this.getChildToken("tlparen");
    }

    public ASTSFExprListNode getASTSFExprList()
    {
        return (ASTSFExprListNode)this.getChild("SFExprList");
    }

    public Token getASTTrparen()
    {
        return this.getChildToken("trparen");
    }

    public ASTSFDummyArgNameListNode getASTSFDummyArgNameList()
    {
        return (ASTSFDummyArgNameListNode)this.getChild("SFDummyArgNameList");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTPointerAssignmentStmtNode(this); }
}
