// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <RdIoCtlSpecList> ::= UnitIdentifier:<UnitIdentifier> tcomma:T_COMMA IoControlSpec:<IoControlSpec>  :production699
 * <RdIoCtlSpecList> ::= UnitIdentifier:<UnitIdentifier> tcomma:T_COMMA FormatIdentifier:<FormatIdentifier>  :production700
 * <RdIoCtlSpecList> ::= IoControlSpec:<IoControlSpec>  :production701
 * <RdIoCtlSpecList> ::= @:<RdIoCtlSpecList> tcomma:T_COMMA IoControlSpec:<IoControlSpec>  :production702
 */
public class ASTRdIoCtlSpecListNode extends ParseTreeNode
{
    public ASTRdIoCtlSpecListNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public int count()
    {
        ParseTreeNode node = this;
        int count = 1;
        while (node.getChild("@") != null)
        {
            count++;
            node = node.getChild("@");
        }
        return count;
    }

    public ASTUnitIdentifierNode getASTUnitIdentifier(int index)
    {
        ASTRdIoCtlSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTRdIoCtlSpecListNode)node.getChild("@");
        return (ASTUnitIdentifierNode)node.getChild("UnitIdentifier");
    }

    public Token getASTTcomma(int index)
    {
        ASTRdIoCtlSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTRdIoCtlSpecListNode)node.getChild("@");
        return node.getChildToken("tcomma");
    }

    public ASTIoControlSpecNode getASTIoControlSpec(int index)
    {
        ASTRdIoCtlSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTRdIoCtlSpecListNode)node.getChild("@");
        return (ASTIoControlSpecNode)node.getChild("IoControlSpec");
    }

    public ASTFormatIdentifierNode getASTFormatIdentifier(int index)
    {
        ASTRdIoCtlSpecListNode node = this;
        for (int i = 0; i < index; i++)
            node = (ASTRdIoCtlSpecListNode)node.getChild("@");
        return (ASTFormatIdentifierNode)node.getChild("FormatIdentifier");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTRdIoCtlSpecListNode(this); }
}
