// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <Rename> ::= tident:T_IDENT teqgreaterthan:T_EQGREATERTHAN UseName:<UseName> 
 */
public class ASTRenameNode extends ParseTreeNode
{
    public ASTRenameNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTident()
    {
        return this.getChildToken("tident");
    }

    public Token getASTTeqgreaterthan()
    {
        return this.getChildToken("teqgreaterthan");
    }

    public ASTUseNameNode getASTUseName()
    {
        return (ASTUseNameNode)this.getChild("UseName");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTRenameNode(this); }
}
