// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <StmtFunctionRange> ::= tlparen:T_LPAREN trparen:T_RPAREN tequals:T_EQUALS Expr:<Expr> teos:T_EOS  :production925
 * <StmtFunctionRange> ::= tlparen:T_LPAREN SFDummyArgNameList:<SFDummyArgNameList> trparen:T_RPAREN tequals:T_EQUALS Expr:<Expr> teos:T_EOS  :production926
 */
public class ASTStmtFunctionRangeNode extends ParseTreeNode
{
    public ASTStmtFunctionRangeNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTlparen()
    {
        return this.getChildToken("tlparen");
    }

    public Token getASTTrparen()
    {
        return this.getChildToken("trparen");
    }

    public Token getASTTequals()
    {
        return this.getChildToken("tequals");
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    public ASTSFDummyArgNameListNode getASTSFDummyArgNameList()
    {
        return (ASTSFDummyArgNameListNode)this.getChild("SFDummyArgNameList");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTStmtFunctionRangeNode(this); }
}
