// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <SubroutinePars> ::= empty
 * <SubroutinePars> ::= SubroutinePar:<SubroutinePar> 
 * <SubroutinePars> ::= SubroutinePars:<SubroutinePars> tcomma:T_COMMA SubroutinePar:<SubroutinePar> 
 */
public class ASTSubroutineParsNode extends ParseTreeNode
{
    public ASTSubroutineParsNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTSubroutineParNode getASTSubroutinePar()
    {
        return (ASTSubroutineParNode)this.getChild("SubroutinePar");
    }

    public ASTSubroutineParsNode getASTSubroutinePars()
    {
        return (ASTSubroutineParsNode)this.getChild("SubroutinePars");
    }

    public Token getASTTcomma()
    {
        return this.getChildToken("tcomma");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSubroutineParsNode(this); }
}
