// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <SavedCommonBlock> ::= tslash:T_SLASH CommonBlockName:<CommonBlockName> tslash2:T_SLASH  :production324
 */
public class ASTSavedCommonBlockNode extends ParseTreeNode
{
    public ASTSavedCommonBlockNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTslash()
    {
        return this.getChildToken("tslash");
    }

    public ASTCommonBlockNameNode getASTCommonBlockName()
    {
        return (ASTCommonBlockNameNode)this.getChild("CommonBlockName");
    }

    public Token getASTTslash2()
    {
        return this.getChildToken("tslash2");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSavedCommonBlockNode(this); }
}
