// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <SubscriptTriplet> ::= tcolon:T_COLON  :production424
 * <SubscriptTriplet> ::= tcolon:T_COLON Expr:<Expr>  :production425
 * <SubscriptTriplet> ::= Expr:<Expr> tcolon:T_COLON  :production426
 * <SubscriptTriplet> ::= Expr:<Expr> tcolon:T_COLON Expr2:<Expr>  :production427
 * <SubscriptTriplet> ::= Expr:<Expr> tcolon:T_COLON Expr2:<Expr> tcolon2:T_COLON Expr3:<Expr>  :production428
 * <SubscriptTriplet> ::= Expr:<Expr> tcolon:T_COLON tcolon2:T_COLON Expr2:<Expr>  :production429
 * <SubscriptTriplet> ::= tcolon:T_COLON Expr:<Expr> tcolon2:T_COLON Expr2:<Expr>  :production430
 * <SubscriptTriplet> ::= tcolon:T_COLON tcolon2:T_COLON Expr:<Expr>  :production431
 */
public class ASTSubscriptTripletNode extends ParseTreeNode
{
    public ASTSubscriptTripletNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public Token getASTTcolon()
    {
        return this.getChildToken("tcolon");
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public ASTExprNode getASTExpr2()
    {
        return (ASTExprNode)this.getChild("Expr2");
    }

    public Token getASTTcolon2()
    {
        return this.getChildToken("tcolon2");
    }

    public ASTExprNode getASTExpr3()
    {
        return (ASTExprNode)this.getChild("Expr3");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSubscriptTripletNode(this); }
}
