// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <SubroutineRange> ::= Body:<Body> EndSubroutineStmt:<EndSubroutineStmt> 
 * <SubroutineRange> ::= EndSubroutineStmt:<EndSubroutineStmt> 
 * <SubroutineRange> ::= BodyPlusInternals:<BodyPlusInternals> EndSubroutineStmt:<EndSubroutineStmt> 
 */
public class ASTSubroutineRangeNode extends ParseTreeNode
{
    public ASTSubroutineRangeNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTBodyNode getASTBody()
    {
        return (ASTBodyNode)this.getChild("Body");
    }

    public ASTEndSubroutineStmtNode getASTEndSubroutineStmt()
    {
        return (ASTEndSubroutineStmtNode)this.getChild("EndSubroutineStmt");
    }

    public ASTBodyPlusInternalsNode getASTBodyPlusInternals()
    {
        return (ASTBodyPlusInternalsNode)this.getChild("BodyPlusInternals");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSubroutineRangeNode(this); }
}
