// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;

import org.eclipse.photran.internal.core.lexer.Token;


/**
 * <SelectCaseStmt> ::= LblDef:<LblDef> Name:<Name> tcolon:T_COLON tselectcase:T_SELECTCASE tlparen:T_LPAREN Expr:<Expr> trparen:T_RPAREN teos:T_EOS 
 * <SelectCaseStmt> ::= LblDef:<LblDef> tselectcase:T_SELECTCASE tlparen:T_LPAREN Expr:<Expr> trparen:T_RPAREN teos:T_EOS 
 * <SelectCaseStmt> ::= LblDef:<LblDef> Name:<Name> tcolon:T_COLON tselect:T_SELECT tcase:T_CASE tlparen:T_LPAREN Expr:<Expr> trparen:T_RPAREN teos:T_EOS 
 * <SelectCaseStmt> ::= LblDef:<LblDef> tselect:T_SELECT tcase:T_CASE tlparen:T_LPAREN Expr:<Expr> trparen:T_RPAREN teos:T_EOS 
 */
public class ASTSelectCaseStmtNode extends ParseTreeNode
{
    public ASTSelectCaseStmtNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTLblDefNode getASTLblDef()
    {
        return (ASTLblDefNode)this.getChild("LblDef");
    }

    public ASTNameNode getASTName()
    {
        return (ASTNameNode)this.getChild("Name");
    }

    public Token getASTTcolon()
    {
        return this.getChildToken("tcolon");
    }

    public Token getASTTselectcase()
    {
        return this.getChildToken("tselectcase");
    }

    public Token getASTTlparen()
    {
        return this.getChildToken("tlparen");
    }

    public ASTExprNode getASTExpr()
    {
        return (ASTExprNode)this.getChild("Expr");
    }

    public Token getASTTrparen()
    {
        return this.getChildToken("trparen");
    }

    public Token getASTTeos()
    {
        return this.getChildToken("teos");
    }

    public Token getASTTselect()
    {
        return this.getChildToken("tselect");
    }

    public Token getASTTcase()
    {
        return this.getChildToken("tcase");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSelectCaseStmtNode(this); }
}
