// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <SFExpr> ::= SFTerm:<SFTerm> 
 * <SFExpr> ::= Sign:<Sign> AddOperand:<AddOperand> 
 * <SFExpr> ::= SFExpr:<SFExpr> AddOp:<AddOp> AddOperand:<AddOperand> 
 */
public class ASTSFExprNode extends ParseTreeNode
{
    public ASTSFExprNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTSFTermNode getASTSFTerm()
    {
        return (ASTSFTermNode)this.getChild("SFTerm");
    }

    public ASTSignNode getASTSign()
    {
        return (ASTSignNode)this.getChild("Sign");
    }

    public ASTAddOperandNode getASTAddOperand()
    {
        return (ASTAddOperandNode)this.getChild("AddOperand");
    }

    public ASTSFExprNode getASTSFExpr()
    {
        return (ASTSFExprNode)this.getChild("SFExpr");
    }

    public ASTAddOpNode getASTAddOp()
    {
        return (ASTAddOpNode)this.getChild("AddOp");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSFExprNode(this); }
}
