// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <SelectCaseRange> ::= SelectCaseBody:<SelectCaseBody> EndSelectStmt:<EndSelectStmt> 
 * <SelectCaseRange> ::= EndSelectStmt:<EndSelectStmt> 
 */
public class ASTSelectCaseRangeNode extends ParseTreeNode
{
    public ASTSelectCaseRangeNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTSelectCaseBodyNode getASTSelectCaseBody()
    {
        return (ASTSelectCaseBodyNode)this.getChild("SelectCaseBody");
    }

    public ASTEndSelectStmtNode getASTEndSelectStmt()
    {
        return (ASTEndSelectStmtNode)this.getChild("EndSelectStmt");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSelectCaseRangeNode(this); }
}
