// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser;


/**
 * <SavedEntity> ::= VariableName:<VariableName> 
 * <SavedEntity> ::= SavedCommonBlock:<SavedCommonBlock> 
 */
public class ASTSavedEntityNode extends ParseTreeNode
{
    public ASTSavedEntityNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTVariableNameNode getASTVariableName()
    {
        return (ASTVariableNameNode)this.getChild("VariableName");
    }

    public ASTSavedCommonBlockNode getASTSavedCommonBlock()
    {
        return (ASTSavedCommonBlockNode)this.getChild("SavedCommonBlock");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTSavedEntityNode(this); }
}
