// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <ThenPart> ::= EndIfStmt:<EndIfStmt>  :production585
 * <ThenPart> ::= ConditionalBody:<ConditionalBody> EndIfStmt:<EndIfStmt>  :production586
 * <ThenPart> ::= ElseIfConstruct:<ElseIfConstruct>  :production587
 * <ThenPart> ::= ConditionalBody:<ConditionalBody> ElseIfConstruct:<ElseIfConstruct>  :production588
 * <ThenPart> ::= ElseConstruct:<ElseConstruct>  :production589
 * <ThenPart> ::= ConditionalBody:<ConditionalBody> ElseConstruct:<ElseConstruct>  :production590
 */
public class ASTThenPartNode extends ParseTreeNode
{
    public ASTThenPartNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTEndIfStmtNode getASTEndIfStmt()
    {
        return (ASTEndIfStmtNode)this.getChild("EndIfStmt");
    }

    public ASTConditionalBodyNode getASTConditionalBody()
    {
        return (ASTConditionalBodyNode)this.getChild("ConditionalBody");
    }

    public ASTElseIfConstructNode getASTElseIfConstruct()
    {
        return (ASTElseIfConstructNode)this.getChild("ElseIfConstruct");
    }

    public ASTElseConstructNode getASTElseConstruct()
    {
        return (ASTElseConstructNode)this.getChild("ElseConstruct");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTThenPartNode(this); }
}
