// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * <WhereConstruct> ::= WhereConstructStmt:<WhereConstructStmt> WhereRange:<WhereRange>  :production540
 */
public class ASTWhereConstructNode extends ParseTreeNode
{
    public ASTWhereConstructNode(Nonterminal nonterminal, Production production)
    {
        super(nonterminal, production);
    }

    public ASTWhereConstructStmtNode getASTWhereConstructStmt()
    {
        return (ASTWhereConstructStmtNode)this.getChild("WhereConstructStmt");
    }

    public ASTWhereRangeNode getASTWhereRange()
    {
        return (ASTWhereRangeNode)this.getChild("WhereRange");
    }

    protected void visitThisNodeUsing(ASTVisitor visitor) { visitor.visitASTWhereConstructNode(this); }
}
