// Generated by Ludwig version 1.0 alpha 6

package org.eclipse.photran.internal.core.parser; import org.eclipse.photran.internal.core.lexer.*;


/**
 * A production in the grammar
 */
public abstract class Production
{
    /**
     * Returns a string describing the production
     */
    public abstract String getDescription();

    abstract void reduce(Parser parser);

    public int getNamedIndex(String name) { return -1; }

    public String toString()
    {
        return getDescription();
    }
}
