#!/bin/sh

ARCH = `uname -p | sed -e 's/powerpc/ppc/' -e 's/ppc64/ppc/' -e 's/i.86/x86/'`
OS = `uname -s | sed -e 's/Darwin/macosx/' -e 's/Linux/linux/'`
INSTALL_DIR = ../org.eclipse.ptp.orte.$(OS).$(ARCH)/bin

cp orte_server $(INSTALL_DIR)
chmod 755 $(INSTALL_DIR)/orte_server

exit 0
