#!/bin/sh
#
# This script is used to set up the project the first time you check it out of
# the CVS repository into Eclipse. It should not be needed to run thereafter.
#

export PARENT=`dirname $PWD`
export ARCH=`uname -p | sed -e 's/powerpc/ppc/' -e 's/ppc64/ppc/' -e 's/i.86/x86/'`
export OS=`uname -s | sed -e 's/Darwin/macosx/' -e 's/Linux/linux/'`
export PREFIX=$PARENT/org.eclipse.ptp.orte.$OS.$ARCH

sh configure --prefix=$PREFIX
exit 0
