//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.09 at 02:55:11 PM CST 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for append complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="append">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="endTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groups" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="indices" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="separator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "append", propOrder = { "value" })
public class Append {

	protected List<String> value;
	@XmlAttribute
	protected String endTag;
	@XmlAttribute
	protected String field;
	@XmlAttribute
	protected String groups;
	@XmlAttribute
	protected String indices;
	@XmlAttribute
	protected String separator;
	@XmlAttribute
	protected String startTag;

	/**
	 * Gets the value of the endTag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEndTag() {
		return endTag;
	}

	/**
	 * Gets the value of the field property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getField() {
		return field;
	}

	/**
	 * Gets the value of the groups property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroups() {
		return groups;
	}

	/**
	 * Gets the value of the indices property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndices() {
		return indices;
	}

	/**
	 * Gets the value of the separator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSeparator() {
		return separator;
	}

	/**
	 * Gets the value of the startTag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStartTag() {
		return startTag;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the value property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getValue() {
		if (value == null) {
			value = new ArrayList<String>();
		}
		return this.value;
	}

	/**
	 * Sets the value of the endTag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEndTag(String value) {
		this.endTag = value;
	}

	/**
	 * Sets the value of the field property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setField(String value) {
		this.field = value;
	}

	/**
	 * Sets the value of the groups property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroups(String value) {
		this.groups = value;
	}

	/**
	 * Sets the value of the indices property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIndices(String value) {
		this.indices = value;
	}

	/**
	 * Sets the value of the separator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSeparator(String value) {
		this.separator = value;
	}

	/**
	 * Sets the value of the startTag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStartTag(String value) {
		this.startTag = value;
	}

}
