//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.15 at 06:57:07 PM CDT 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for arglist complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="arglist">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arg" type="{http://org.eclipse.ptp/rm}arg" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dynamicAppend" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arglist", propOrder = { "arg" })
public class Arglist {

	@XmlElement(required = true)
	protected List<Arg> arg;
	@XmlAttribute
	protected Boolean dynamicAppend;

	/**
	 * Gets the value of the arg property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the arg property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArg().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Arg }
	 * 
	 * 
	 */
	public List<Arg> getArg() {
		if (arg == null) {
			arg = new ArrayList<Arg>();
		}
		return this.arg;
	}

	/**
	 * Gets the value of the dynamicAppend property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isDynamicAppend() {
		if (dynamicAppend == null) {
			return false;
		} else {
			return dynamicAppend;
		}
	}

	/**
	 * Sets the value of the dynamicAppend property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setDynamicAppend(Boolean value) {
		this.dynamicAppend = value;
	}

}
