//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.03 at 07:31:36 PM CST 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * In the set, append, add and put elements, value, values and keys refer to the
 * group index of the matched regex, or the index of the split array. A
 * comma-delimited list of single integers or ranges expressed using a colon
 * (e.g, 1:5); 'L' by convention refers to the length of the array or number of
 * groups; expressions like 'L-4' are permissible. Set = single group; Add = add
 * each group separately to a list; Append = concatenate the groups into a
 * single string; Put = put key-value pairs into map.
 * 
 * 
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}set"/>
 *         &lt;element ref="{}append"/>
 *         &lt;element ref="{}add"/>
 *         &lt;element ref="{}put"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "set", "append", "add", "put" })
@XmlRootElement(name = "assign")
public class Assign {

	protected Set set;
	protected Append append;
	protected Add add;
	protected Put put;
	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the add property.
	 * 
	 * @return possible object is {@link Add }
	 * 
	 */
	public Add getAdd() {
		return add;
	}

	/**
	 * Gets the value of the append property.
	 * 
	 * @return possible object is {@link Append }
	 * 
	 */
	public Append getAppend() {
		return append;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the value of the put property.
	 * 
	 * @return possible object is {@link Put }
	 * 
	 */
	public Put getPut() {
		return put;
	}

	/**
	 * Gets the value of the set property.
	 * 
	 * @return possible object is {@link Set }
	 * 
	 */
	public Set getSet() {
		return set;
	}

	/**
	 * Sets the value of the add property.
	 * 
	 * @param value
	 *            allowed object is {@link Add }
	 * 
	 */
	public void setAdd(Add value) {
		this.add = value;
	}

	/**
	 * Sets the value of the append property.
	 * 
	 * @param value
	 *            allowed object is {@link Append }
	 * 
	 */
	public void setAppend(Append value) {
		this.append = value;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Sets the value of the put property.
	 * 
	 * @param value
	 *            allowed object is {@link Put }
	 * 
	 */
	public void setPut(Put value) {
		this.put = value;
	}

	/**
	 * Sets the value of the set property.
	 * 
	 * @param value
	 *            allowed object is {@link Set }
	 * 
	 */
	public void setSet(Set value) {
		this.set = value;
	}

}
