//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.04 at 11:30:15 PM CST 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}match-group" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}match" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="delim" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromEnd" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="includeDelim" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="repeat" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="save" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "matchGroup", "match" })
@XmlRootElement(name = "read")
public class Read {

	@XmlElement(name = "match-group")
	protected List<MatchGroup> matchGroup;
	protected List<Match> match;
	@XmlAttribute
	protected Boolean all;
	@XmlAttribute
	protected String delim;
	@XmlAttribute
	protected Boolean fromEnd;
	@XmlAttribute
	protected Boolean includeDelim;
	@XmlAttribute
	protected BigInteger limit;
	@XmlAttribute
	protected Integer repeat;
	@XmlAttribute
	protected Integer save;

	/**
	 * Gets the value of the delim property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDelim() {
		return delim;
	}

	/**
	 * Gets the value of the limit property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getLimit() {
		return limit;
	}

	/**
	 * Gets the value of the match property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the match property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMatch().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Match }
	 * 
	 * 
	 */
	public List<Match> getMatch() {
		if (match == null) {
			match = new ArrayList<Match>();
		}
		return this.match;
	}

	/**
	 * Gets the value of the matchGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the matchGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMatchGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MatchGroup }
	 * 
	 * 
	 */
	public List<MatchGroup> getMatchGroup() {
		if (matchGroup == null) {
			matchGroup = new ArrayList<MatchGroup>();
		}
		return this.matchGroup;
	}

	/**
	 * Gets the value of the repeat property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public int getRepeat() {
		if (repeat == null) {
			return 0;
		} else {
			return repeat;
		}
	}

	/**
	 * Gets the value of the save property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public int getSave() {
		if (save == null) {
			return 0;
		} else {
			return save;
		}
	}

	/**
	 * Gets the value of the all property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isAll() {
		if (all == null) {
			return false;
		} else {
			return all;
		}
	}

	/**
	 * Gets the value of the fromEnd property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isFromEnd() {
		if (fromEnd == null) {
			return false;
		} else {
			return fromEnd;
		}
	}

	/**
	 * Gets the value of the includeDelim property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isIncludeDelim() {
		if (includeDelim == null) {
			return false;
		} else {
			return includeDelim;
		}
	}

	/**
	 * Sets the value of the all property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setAll(Boolean value) {
		this.all = value;
	}

	/**
	 * Sets the value of the delim property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDelim(String value) {
		this.delim = value;
	}

	/**
	 * Sets the value of the fromEnd property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setFromEnd(Boolean value) {
		this.fromEnd = value;
	}

	/**
	 * Sets the value of the includeDelim property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIncludeDelim(Boolean value) {
		this.includeDelim = value;
	}

	/**
	 * Sets the value of the limit property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setLimit(BigInteger value) {
		this.limit = value;
	}

	/**
	 * Sets the value of the repeat property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setRepeat(Integer value) {
		this.repeat = value;
	}

	/**
	 * Sets the value of the save property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setSave(Integer value) {
		this.save = value;
	}

}
