//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.20 at 11:36:36 AM CDT 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * It is assumed that the xml instance of the schema will bear a name which
 * sufficiently distinguishes it from others of a similar type; e.g.,
 * pbs-torque-v_2.3.7_abe is specific to an installation on the host abe,
 * ll-v_4.0 suits all installations of LoadLeveler version 4, etc.
 * 
 * 
 * <p>
 * Java class for resource-manager-data complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="resource-manager-data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="site-data" type="{http://org.eclipse.ptp/rm}site-type" minOccurs="0"/>
 *         &lt;element name="control-data" type="{http://org.eclipse.ptp/rm}control-type"/>
 *         &lt;element name="monitor-data" type="{http://org.eclipse.ptp/rm}monitor-type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resource-manager-data", propOrder = { "siteData", "controlData", "monitorData" })
public class ResourceManagerData {

	@XmlElement(name = "site-data")
	protected SiteType siteData;
	@XmlElement(name = "control-data", required = true)
	protected ControlType controlData;
	@XmlElement(name = "monitor-data", required = true)
	protected MonitorType monitorData;
	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the controlData property.
	 * 
	 * @return possible object is {@link ControlType }
	 * 
	 */
	public ControlType getControlData() {
		return controlData;
	}

	/**
	 * Gets the value of the monitorData property.
	 * 
	 * @return possible object is {@link MonitorType }
	 * 
	 */
	public MonitorType getMonitorData() {
		return monitorData;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the value of the siteData property.
	 * 
	 * @return possible object is {@link SiteType }
	 * 
	 */
	public SiteType getSiteData() {
		return siteData;
	}

	/**
	 * Sets the value of the controlData property.
	 * 
	 * @param value
	 *            allowed object is {@link ControlType }
	 * 
	 */
	public void setControlData(ControlType value) {
		this.controlData = value;
	}

	/**
	 * Sets the value of the monitorData property.
	 * 
	 * @param value
	 *            allowed object is {@link MonitorType }
	 * 
	 */
	public void setMonitorData(MonitorType value) {
		this.monitorData = value;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Sets the value of the siteData property.
	 * 
	 * @param value
	 *            allowed object is {@link SiteType }
	 * 
	 */
	public void setSiteData(SiteType value) {
		this.siteData = value;
	}

}
