//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.03 at 07:31:36 PM CST 
//

package org.eclipse.ptp.rm.jaxb.core.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}grid-data" minOccurs="0"/>
 *         &lt;element ref="{}grid-layout" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}style" minOccurs="0"/>
 *         &lt;element ref="{}column-data" minOccurs="0"/>
 *         &lt;element name="initial-rows" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="column-text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="type" default="table">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="table"/>
 *             &lt;enumeration value="tree"/>
 *             &lt;enumeration value="checkboxTable"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "gridData", "gridLayout", "label", "style", "columnData", "initialRows" })
@XmlRootElement(name = "viewer")
public class Viewer {

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="row" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="column-text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "row" })
	public static class InitialRows {

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="column-text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "columnText" })
		public static class Row {

			@XmlElement(name = "column-text", required = true)
			protected List<String> columnText;

			/**
			 * Gets the value of the columnText property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the columnText property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getColumnText().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getColumnText() {
				if (columnText == null) {
					columnText = new ArrayList<String>();
				}
				return this.columnText;
			}

		}

		@XmlElement(required = true)
		protected List<Viewer.InitialRows.Row> row;

		/**
		 * Gets the value of the row property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the row property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getRow().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Viewer.InitialRows.Row }
		 * 
		 * 
		 */
		public List<Viewer.InitialRows.Row> getRow() {
			if (row == null) {
				row = new ArrayList<Viewer.InitialRows.Row>();
			}
			return this.row;
		}

	}

	@XmlElement(name = "grid-data")
	protected GridData gridData;
	@XmlElement(name = "grid-layout")
	protected GridLayout gridLayout;
	protected String label;
	protected Style style;
	@XmlElement(name = "column-data")
	protected ColumnData columnData;
	@XmlElement(name = "initial-rows")
	protected Viewer.InitialRows initialRows;
	@XmlAttribute
	protected Boolean editable;

	@XmlAttribute
	protected String type;

	/**
	 * Gets the value of the columnData property.
	 * 
	 * @return possible object is {@link ColumnData }
	 * 
	 */
	public ColumnData getColumnData() {
		return columnData;
	}

	/**
	 * Gets the value of the gridData property.
	 * 
	 * @return possible object is {@link GridData }
	 * 
	 */
	public GridData getGridData() {
		return gridData;
	}

	/**
	 * Gets the value of the gridLayout property.
	 * 
	 * @return possible object is {@link GridLayout }
	 * 
	 */
	public GridLayout getGridLayout() {
		return gridLayout;
	}

	/**
	 * Gets the value of the initialRows property.
	 * 
	 * @return possible object is {@link Viewer.InitialRows }
	 * 
	 */
	public Viewer.InitialRows getInitialRows() {
		return initialRows;
	}

	/**
	 * Gets the value of the label property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Gets the value of the style property.
	 * 
	 * @return possible object is {@link Style }
	 * 
	 */
	public Style getStyle() {
		return style;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		if (type == null) {
			return "table";//$NON-NLS-1$
		} else {
			return type;
		}
	}

	/**
	 * Gets the value of the editable property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isEditable() {
		if (editable == null) {
			return true;
		} else {
			return editable;
		}
	}

	/**
	 * Sets the value of the columnData property.
	 * 
	 * @param value
	 *            allowed object is {@link ColumnData }
	 * 
	 */
	public void setColumnData(ColumnData value) {
		this.columnData = value;
	}

	/**
	 * Sets the value of the editable property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setEditable(Boolean value) {
		this.editable = value;
	}

	/**
	 * Sets the value of the gridData property.
	 * 
	 * @param value
	 *            allowed object is {@link GridData }
	 * 
	 */
	public void setGridData(GridData value) {
		this.gridData = value;
	}

	/**
	 * Sets the value of the gridLayout property.
	 * 
	 * @param value
	 *            allowed object is {@link GridLayout }
	 * 
	 */
	public void setGridLayout(GridLayout value) {
		this.gridLayout = value;
	}

	/**
	 * Sets the value of the initialRows property.
	 * 
	 * @param value
	 *            allowed object is {@link Viewer.InitialRows }
	 * 
	 */
	public void setInitialRows(Viewer.InitialRows value) {
		this.initialRows = value;
	}

	/**
	 * Sets the value of the label property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabel(String value) {
		this.label = value;
	}

	/**
	 * Sets the value of the style property.
	 * 
	 * @param value
	 *            allowed object is {@link Style }
	 * 
	 */
	public void setStyle(Style value) {
		this.style = value;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

}
